#!/usr/bin/env bash
# Bash script to transfer files to the server

if  [ "$#" -lt 4 ]; then
     echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
     exit 1
fi

# Assigning parameters to values
file_path=$1
server_ip=$2
usernane=$3
ssh_key_path=$4

# Use sco to transfer the file to the user's home directory in the server
scp -o StrictHostHeyChecking=no -i

#Check the exit status of the scp command
if [ $? -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "Error: File transfer failed."
fi
