#!/usr/bin/env bash
# Bash script to transfer files to the server

 Assigning parameters to values
file_path=$1
server_ip=$2
usernane=$3
ssh_key_path=$4
if  [ "$#" -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	sed -i '$ a \    StrictHostKeyChecking no' /etc/ssh/ssh_config
	scp -i "$ssh_key_path" "$file_path" "$username"@"$server_ip":~/
fi

