#!/usr/bin/env bash
#installs ngix
#Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y install -y nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx restart
