#!/usr/bin/env bash
# A bash string that pings an IP address passed as an arguement
# Requirements:
# accepts strings as arguemnts
# displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
# if no argument passed
# Ping the IP 5 times

if [ "$#" -eq 0 ]; then
	echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
else
	ping -c 5 "$1"
fi
