#!/usr/bin/env bash
# Configuring the nginx server to listen in port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
