#!/usr/bin/env bash
# A Bash script that displays a list of currently running processes.
ps aux --forest | awk 'BEGIN {printf "%-10s %-5s %-20s\n", "USER", "RSS", "COMMAND"} NR <= 50 {printf "%-10s %-5s %-20s\n", $1, $6, $11}'
