#!/usr/bin/env bash
#read and cut

while IFS=: read -r username _ uid _ _ home _; do
	echo "The user $username is part of the $uid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
