#!/usr/bin/env bash
#Prints a string 10 times, using while loop

i=0

while [ $i != 10 ]; do
	if [ $i = 8 ]; then
		echo "Best School"
		echo "Hi"
	fi

	if [ $i != 8 ]; then
		echo "Best School"
	fi

	i=$((i + 1))
done
