#!/usr/bin/env bash
#Prints a string 10 times, using while loop

i=1

while [ $i != 11 ]; do
	if [ $i = 4 ]; then
		echo "bad luck"
	elif [ $i = 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi

	i=$((i + 1))
done
